name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
      - stage
  pull_request:
    branches:
      - develop
      - main
      - stage

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: myregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deployments/docker/Dockerfile.prod
        push: true
        tags: myregistry.azurecr.io/myapp:${{ github.sha }}
        
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo "Running tests..."
        go test ./... -coverprofile=coverage.txt
        
  deploy-dev:
    needs: [build, test]
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Development
      uses: azure/k8s-deploy@v1.3
      with:
        manifests: |
          deployments/kubernetes/configmap.yaml
          deployments/kubernetes/secrets.yaml
          deployments/kubernetes/deployment.yaml
          deployments/kubernetes/service.yaml
        images: |
          myregistry.azurecr.io/myapp:${{ github.sha }}
        namespace: myapp
        
  deploy-prod:
    needs: [build, test]
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Production
      uses: azure/k8s-deploy@v1.3
      with:
        manifests: |
          deployments/kubernetes/configmap.yaml
          deployments/kubernetes/secrets.yaml
          deployments/kubernetes/deployment.yaml
          deployments/kubernetes/service.yaml
        images: |
          myregistry.azurecr.io/myapp:${{ github.sha }}
        namespace: myapp